/* EDIT THIS LIST to update the public register and portal access. power is 1–10. */
const officials=[
 {slug:'william',name:'William',rank:'President',title:'President William',division:'Executive Government',power:10,status:'In Office'},
 {slug:'braedyn',name:'Braedyn',rank:'Premier',title:'Premier Braedyn',division:'Honkan Socialist Republics',power:9,status:'In Office',roles:['Head of the Honkan Socialist Republics']},
 {slug:'jacob-leys',name:'Jacob Leys',rank:'Head of CSS',title:'Jacob Leys',division:'Committee of State Security',power:8,status:'Active',roles:['Deputy Head of the Honkan Socialist Republics']},
 {slug:'emma',name:'Emma',rank:'Chairman of the Bureau of Intelligence',title:'Emma',division:'Bureau of Intelligence',power:7,status:'Active'},
 {slug:'christain-schubert',name:'Christain Schubert',rank:'Chairman of Council Members',title:'Christain Schubert',division:'Council Members',power:7,status:'Active'},
 {slug:'siddhant-pant',name:'Siddhant Pant',rank:'Admiral of the Navy',title:'Siddhant Pant',division:'Treekian Navy',power:7,status:'Active Service'},
 {slug:'ben',name:'Ben',rank:'General of the Army',title:'General Ben',division:'Treekian Army',power:7,status:'Active Service'},
 {slug:'nico-cage',name:'Nico Cage',rank:'Air Marshal',title:'Air Marshal Nico Cage',division:'Treekian Air Force',power:7,status:'Active Service'},
 {slug:'matthew',name:'Matthew',rank:'Head of Publicity',title:'Matthew',division:'Ministry of Publicity',power:6,status:'Active'},
 {slug:'christian',name:'Christian',rank:'General of Foreign Affairs',title:'General Christian',division:'Ministry of Foreign Affairs',power:6,status:'Active'},
 {slug:'noah',name:'Noah',rank:'Director',title:'Director Noah',division:'National Nuclear Programme',power:6,status:'Active'}
];
const pages={
 home:['Official Government Portal','New Treekian Union of the Socialist Republics','Government information, services, institutions and public records.'],
 government:['Executive leadership','Government','National leadership, ministries and institutions.'], officials:['Official register','High-Ranked Officials','Public register of senior state personnel.'],defence:['Ministry of Defence','Treekian Armed Forces','Defending the New Treekian Union.'],economy:['National planning','Treekian Economy','National planning, currency and public statistics.'],culture:['Identity and tradition','Treekian Culture','Language, symbols and national character.'],constitution:['Law and state','Constitution of Treekia','Foundational law of the republics.'],ministries:['Government departments','Government Ministries','Administrative departments of the Government.'],army:['Treekian Armed Forces','Treekian Army','Strength, readiness and discipline.'],airforce:['Treekian Armed Forces','Treekian Air Force','Air superiority, readiness and precision.'],navy:['Treekian Armed Forces','Treekian Navy','Service, vigilance and maritime security.'],rr:['Security and intelligence','Committee of State Security','Safeguarding national stability and sovereignty.'],president:['Executive leadership','Office of the President','Head of State and national executive office.'],login:['Staff access','Staff Portal','Authorised personnel directory.'],portal:['Internal records','Government Staff Portal','Demonstration portal for official departments.']};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(h,p,href)=>`<a class="card" href="${href}"><h3>${h}</h3><p>${p}</p><span class="link-label">View page →</span></a>`;
const section=(h,body)=>`<section><h2>${h}</h2>${body}</section>`;
const table=rows=>`<table class="data-table">${rows.map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td></tr>`).join('')}</table>`;
const cards=items=>`<div class="grid">${items.map(x=>card(...x)).join('')}</div>`;
function officialCard(o){return `<a class="official" href="official-${o.slug}.html"><span class="badge">${esc(o.division)}</span><h3>${esc(o.title)}</h3><p><strong>${esc(o.rank)}</strong></p><p>${esc(o.status)}</p><div class="power"><span>Authority ${o.power}/10</span><span class="meter"><i style="width:${o.power*10}%"></i></span></div></a>`}
function profile(o){if(o.slug==='jacob-leys')return section('Official record',`<div class="profile"><div class="profile-panel"><span class="badge">Committee of State Security</span><h2>Official Record</h2>${table([['Position','Chairman of the Remorics Reich'],['Public Office','Head of CSS'],['Additional Office','Deputy Head of the Honkan Socialist Republics'],['Status','Active'],['Authority',o.power+'/10']])}</div><div class="redacted">Identity Redacted<br><small>State Security Record</small></div></div>`);return section('Official profile',`<div class="profile"><div class="profile-panel"><span class="badge">${esc(o.division)}</span><h2>${esc(o.title)}</h2>${table([['Rank',esc(o.rank)],['Name',esc(o.name)],['Division',esc(o.division)],['Status',esc(o.status)],['Authority',`${o.power}/10`],...(o.roles||[]).map((x,i)=>['Additional Office '+(i+1),esc(x)])])}</div><div class="notice"><strong>Official Register</strong><br>Authority scale is a public indication of this office’s seniority.</div></div>`)}
function content(page){
 const o=officials.find(x=>'official-'+x.slug===page);if(o)return profile(o);
 if(page==='home')return section('Welcome','<p class="intro">Welcome to the official Government Portal of the New Treekian Union of the Socialist Republics. This website provides official information regarding the Government, Armed Forces, ministries, national policies, economy, culture, and constitutional framework of Treekia.</p>')+section('Government Services',cards([['Government','View the President, ministries and government structure.','government.html'],['High-Ranked Officials','View senior officials, ranks, divisions and official records.','officials.html'],['Defence','Information regarding the Treekian Armed Forces.','defence.html'],['Economy','National currency, population and statistics.','economy.html'],['Culture','Official languages, national symbols and traditions.','culture.html'],['Constitution','Read the constitutional documents of Treekia.','constitution.html']]))+section('National Overview',table([['Official Name','New Treekian Union of the Socialist Republics'],['Common Name','Treekia'],['President','William'],['Premier','Braedyn'],['Population','14'],['Currency','Treek (₸)'],['ISO Code','TRK'],['Official Languages','Russian, English'],['Driving Side','Left'],['Time Zone','TST (UTC+12) / TDT (UTC+13)']]));
 if(page==='government')return section('Government Overview','<p class="intro">The Government of the New Treekian Union of the Socialist Republics is headed by the President and supported by the Premier, ministries, the Armed Forces, and the Committee of State Security.</p>')+section('Executive Leadership',cards([['President','President William — Head of State','president.html'],['Premier','Premier Braedyn — Head of the Honkan Socialist Republics','official-braedyn.html'],['Ministries','Government departments responsible for national administration.','ministries.html'],['Committee of State Security','Internal security and intelligence.','rr.html'],['High-Ranked Officials','Official register of senior state personnel.','officials.html']]))+section('Government Officials',table([['President','William'],['Premier','Braedyn'],['Head of CSS','Jacob Leys'],['Chairman of the Bureau of Intelligence','Emma'],['Chairman of Council Members','Christain Schubert'],['General of the Army','Ben'],['Air Marshal','Nico Cage'],['Admiral of the Navy','Siddhant Pant'],['Head of Publicity','Matthew'],['General of Foreign Affairs','Christian'],['Head of Nuclear Programme','Noah']]));
 if(page==='officials')return section('Official Register','<p class="intro">This page lists senior officials of the New Treekian Union of the Socialist Republics. Authority is rated from 1–10 for a clear public view of each office’s seniority.</p>')+section('Senior Leadership',`<div class="official-grid">${officials.map(officialCard).join('')}</div>`);
 if(page==='defence')return section('Overview','<p class="intro">The Treekian Armed Forces are responsible for the defence of the New Treekian Union of the Socialist Republics. The Armed Forces consist of the Army, Air Force and Navy, operating under the authority of the President as Commander-in-Chief.</p>')+section('Military Branches',cards([['Army','General Ben','army.html'],['Air Force','Air Marshal Nico Cage','airforce.html'],['Navy','Admiral Siddhant Pant','navy.html']]))+section('Command Structure',table([['Commander-in-Chief','President William'],['General of the Army','Ben'],['Air Marshal','Nico Cage'],['Admiral of the Navy','Siddhant Pant']]));
 if(page==='army')return branch('The Treekian Army is the land warfare branch of the Treekian Armed Forces. It is responsible for ground defence, armoured operations, national security support, and military readiness.',[['Rank','General of the Army'],['Name','Ben'],['Division','Army'],['Status','Active Service']],[['T-55 Main Battle Tank','In Service'],['BTR-80 Armoured Personnel Carrier','In Service'],['BMP-1 Infantry Fighting Vehicle','In Service'],['T-60 Light Tank','On Order']]);
 if(page==='airforce')return branch('The Treekian Air Force protects national airspace, supports military operations, conducts aerial reconnaissance and provides strategic air capability.',[['Rank','Air Marshal'],['Name','Nico Cage'],['Division','Air Force'],['Status','Active Service']],[['Paper Aircraft','Operational'],['MiG-15 Photograph','Display Asset']]);
 if(page==='navy')return branch('The Treekian Navy is the maritime branch of the Treekian Armed Forces. It supports national maritime interests, coastal security and future naval development.',[['Rank','Admiral of the Navy'],['Name','Siddhant Pant'],['Division','Navy'],['Status','Active Service']],[['Paper Boat','Operational']]);
 if(page==='economy')return section('Overview','<p class="intro">The Treekian economy is centrally structured under government oversight. It operates using the national currency, the Treek (₸), and is managed through coordinated national planning and administration.</p>')+section('Key Indicators',table([['Population','14'],['Currency','Treek (₸)'],['ISO Code','TRK'],['Economic Model','Socialist Planned Economy'],['Trade Status','Internal / Micronational'],['Primary Industries','Administration, Defence, Public Services']]));
 if(page==='culture')return section('Overview','<p class="intro">The culture of the New Treekian Union of the Socialist Republics is shaped by its national identity, shared traditions, and symbolic institutions. It reflects unity, simplicity, and collective national pride.</p>')+section('National Identity',cards([['Official Languages','Russian, English','#'],['National Animal','Yellow-crested Warbler','#'],['National Dish',"My mate's dad's pizza",'#'],['National Sport','Football','#']]));
 if(page==='constitution')return ['Preamble|We, the people of the New Treekian Union of the Socialist Republics, establish justice, ensure national stability, provide for the common defence, and secure liberty and order.','Article I — The State|The New Treekian Union of the Socialist Republics is a sovereign socialist state governed under a centralized system of administration.','Article II — The President|The President is the Head of State and Commander-in-Chief of the Armed Forces.','Article III — Government Structure|The Government shall consist of ministries, armed forces, and administrative bodies.','Article IV — Armed Forces|The Treekian Armed Forces are responsible for the defence of the nation.','Article V — State Security|The Committee of State Security is responsible for internal security, intelligence, and sovereignty protection.'].map(x=>{const [h,p]=x.split('|');return section(h,`<p class="intro">${p}</p>`)}).join('');
 if(page==='rr')return section('Overview','<p class="intro">The Committee of State Security is the national security and intelligence organisation of the New Treekian Union of the Socialist Republics.</p>')+section('Leadership',table([['Public Name','Committee of State Security'],['Senior Official','Redacted'],['Public Office','Head of CSS'],['Reports To','Premier Braedyn'],['Status','Active']]))+'<div class="notice">Certain records are withheld from the public register.</div>';
 if(page==='ministries')return section('Overview','<p class="intro">The ministries of the New Treekian Union of the Socialist Republics are responsible for national administration and implementation of government policy.</p>')+section('Government Departments',cards([['Ministry of Foreign Affairs','Minister: General Christian. Responsible for diplomatic relations, international communications and foreign policy.','#'],['Ministry of Publicity','Minister: Matthew. Responsible for official government communications and public information.','#'],['National Nuclear Programme','Director: Noah. Responsible for research and administration of the national nuclear programme.','#'],['Committee of State Security','Head: Jacob Leys. Responsible for internal security, intelligence and national protection.','rr.html']]))+section('Current Leadership',table([['Foreign Affairs','General Christian'],['Ministry of Publicity','Matthew'],['National Nuclear Programme','Noah'],['Committee of State Security','Redacted']]));
 if(page==='president')return section('President William','<p class="intro">President William serves as the Head of State of the New Treekian Union of the Socialist Republics and is responsible for overall leadership of the Government and Armed Forces.</p>')+section('Office',table([['Office','Head of State'],['Command','Commander-in-Chief'],['Authority','10/10']]));
 if(page==='login')return section('Staff Login','<div class="portal-panel"><p>Enter the full name of a listed official to access the demonstration staff portal.</p><form class="form" id="login-form"><label for="staff-name">Name</label><input id="staff-name" autocomplete="name" placeholder="Enter an official’s name" required><button class="button">Enter Portal</button><p class="message" id="login-message"></p></form></div>');
 return section('Internal Services',cards(['Personnel Register','Security Notices','Ministry Reports','Defence Records'].map(x=>[x,'Demonstration record area.','#'])));
}
function branch(intro,command,inventory){return section('Overview',`<p class="intro">${intro}</p>`)+section('Command',table(command))+section('Mission','<p class="intro">To defend the New Treekian Union of the Socialist Republics through professional service, readiness, and national protection.</p>')+section('Inventory',table(inventory))+section('Core Values',cards([['Readiness','Prepared to respond whenever required.','#'],['Discipline','Professional standards in all operations.','#'],['Service','Service to the nation above self.','#'],['Unity','Working together for national defence.','#']]))}
function render(){const page=document.body.dataset.page||'home';const p=pages[page]||pages.home;document.title=`${p[1]} | New Treekian Union`;const nav=[['Home','index.html','home'],['Government','government.html','government'],['Officials','officials.html','officials'],['Defence','defence.html','defence'],['Economy','economy.html','economy'],['Culture','culture.html','culture'],['Constitution','constitution.html','constitution'],['Staff Portal','login.html','login']];document.body.innerHTML=`<header class="site-header"><div class="masthead"><a class="mark" href="index.html" aria-label="Home">NTU</a><div><p class="eyebrow">Official Government Portal</p><h1>Government of the New Treekian Union</h1><p>Union of Socialist Republics</p></div><button class="menu-button" aria-expanded="false">Menu</button></div><nav class="nav">${nav.map(x=>`<a class="${x[2]===page?'active':''} ${x[2]==='login'?'portal':''}" href="${x[1]}">${x[0]}</a>`).join('')}</nav></header><section class="hero"><div class="hero-inner"><p class="eyebrow">${p[0]}</p><h2>${p[1]}</h2><p>${p[2]}</p></div></section><main>${content(page)}</main><footer class="site-footer"><strong>Committee of State Security</strong><br>Official Government Portal<br>© 2026 Government of Treekia</footer>`;document.querySelector('.menu-button')?.addEventListener('click',e=>{const n=document.querySelector('.nav'),open=n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});document.querySelector('#login-form')?.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#staff-name');const user=officials.find(o=>o.name.toLocaleLowerCase()===input.value.trim().toLocaleLowerCase());document.querySelector('#login-message').textContent=user?`Access granted: ${user.title} — authority ${user.power}/10.`:'Name not found in the official register.';if(user)setTimeout(()=>location.href='portal.html',700)})}document.addEventListener('DOMContentLoaded',render);
